spring:
  application:
    name: spring-boot-owen
  datasource:
    url: jdbc:mysql://a.b.c.d:3306/dabtabse?useUnicode=true&characterEncoding=utf-8
    username: xxxxx
    password: xxxxxxx
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    

server:
  port: 80

logging:
  level: INFO
  
